import os

path = r"C:\Users\Admin\Downloads\Auspoty\auspoty-flutter\lib\main.dart"

lines = [
"import 'dart:async';",
"import 'dart:io';",
"import 'package:flutter/material.dart';",
"import 'package:flutter/services.dart';",
"import 'package:flutter_inappwebview/flutter_inappwebview.dart';",
"import 'package:wakelock_plus/wakelock_plus.dart';",
"import 'package:shared_preferences/shared_preferences.dart';",
"import 'package:url_launcher/url_launcher.dart';",
"import 'package:path_provider/path_provider.dart';",
"import 'package:permission_handler/permission_handler.dart';",
"import 'package:http/http.dart' as http;",
"import 'package:audio_service/audio_service.dart';",
"import 'models/song.dart';",
"import 'screens/player.dart';",
"import 'services/audio.dart';",
"",
"const _base =",
"    'https://clone2-git-master-yusrilrizky121-codes-projects.vercel.app';",
"",
"void main() async {",
"  WidgetsFlutterBinding.ensureInitialized();",
"  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(",
"    statusBarColor: Colors.transparent,",
"    statusBarIconBrightness: Brightness.light,",
"    systemNavigationBarColor: Color(0xFF0a0a0f),",
"    systemNavigationBarIconBrightness: Brightness.light,",
"  ));",
"  if (Platform.isAndroid) {",
"    try { await Permission.notification.request(); } catch (_) {}",
"  }",
"  try { await initAudio(); } catch (_) {}",
"  runApp(const AuspotyApp());",
"}",
"",
"class AuspotyApp extends StatelessWidget {",
"  const AuspotyApp({super.key});",
"  @override",
"  Widget build(BuildContext context) => MaterialApp(",
"        title: 'Auspoty',",
"        debugShowCheckedModeBanner: false,",
"        theme: ThemeData(",
"          brightness: Brightness.dark,",
"          scaffoldBackgroundColor: const Color(0xFF0a0a0f),",
"          colorScheme: const ColorScheme.dark(",
"            primary: Color(0xFF7c6af7),",
"            secondary: Color(0xFF7c6af7),",
"          ),",
"          useMaterial3: true,",
"        ),",
"        home: const _WebViewHome(),",
"      );",
"}",
"",
"Song? _currentSong;",
"",
"class _WebViewHome extends StatefulWidget {",
"  const _WebViewHome();",
"  @override",
"  State<_WebViewHome> createState() => _WebViewHomeState();",
"}",
"",
"class _WebViewHomeState extends State<_WebViewHome>",
"    with WidgetsBindingObserver {",
"  InAppWebViewController? _wvc;",
"  bool _loading = true;",
"  DateTime? _lastBack;",
"",
"  @override",
"  void initState() {",
"    super.initState();",
"    WidgetsBinding.instance.addObserver(this);",
"  }",
"",
"  @override",
"  void dispose() {",
"    WidgetsBinding.instance.removeObserver(this);",
"    super.dispose();",
"  }",
"",
"  @override",
"  void didChangeAppLifecycleState(AppLifecycleState state) {",
"    if (state == AppLifecycleState.resumed && _currentSong != null) {",
"      final playing = audioHandler.isPlaying;",
"      _wvc?.evaluateJavascript(source: \"\"\"",
"        (function(){",
"          if(typeof updatePlayPauseBtn==='function') updatePlayPauseBtn($playing);",
"        })();",
"      \"\"\");",
"    }",
"  }",
"",
"  Future<bool> _onBack() async {",
"    if (_wvc == null) return true;",
"    final r = await _wvc!.evaluateJavascript(source: \"\"\"",
"      (function(){",
"        var m=['playerModal','lyricsModal','editProfileModal','createPlaylistModal',",
"               'addToPlaylistModal','commentsModal','pickerModal'];",
"        for(var i=0;i<m.length;i++){",
"          var e=document.getElementById(m[i]);",
"          if(e&&e.style.display!==''&&e.style.display!=='none') return 'modal:'+m[i];",
"        }",
"        var a=document.querySelector('.view-section.active');",
"        return a?a.id:'view-home';",
"      })()",
"    \"\"\");",
"    final s = (r ?? 'view-home').replaceAll('\"', '').trim();",
"    if (s.startsWith('modal:')) {",
"      final id = s.split(':')[1];",
"      await _wvc!.evaluateJavascript(source: \"\"\"",
"        (function(){",
"          var e=document.getElementById('$id');",
"          if(e) e.style.display='none';",
"          if('$id'==='lyricsModal'){",
"            if(typeof closeLyricsToPlayer==='function') closeLyricsToPlayer();",
"            else if(typeof closeLyrics==='function') closeLyrics();",
"          }",
"        })()",
"      \"\"\");",
"      return false;",
"    }",
"    if (!['view-home','view-search','view-library','view-settings'].contains(s)) {",
"      await _wvc!.evaluateJavascript(",
"          source: \"if(typeof switchView==='function') switchView('home');\");",
"      return false;",
"    }",
"    final now = DateTime.now();",
"    if (_lastBack == null || now.difference(_lastBack!) > const Duration(seconds: 2)) {",
"      _lastBack = now;",
"      if (mounted) {",
"        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(",
"          content: Text('Tekan sekali lagi untuk keluar'),",
"          duration: Duration(seconds: 2),",
"          behavior: SnackBarBehavior.floating,",
"        ));",
"      }",
"      return false;",
"    }",
"    return true;",
"  }",
"",
"  Future<void> _download(String videoId, String title) async {",
"    if (Platform.isAndroid) {",
"      try { await Permission.storage.request(); } catch (_) {}",
"    }",
"    try {",
"      final r = await http",
"          .post(Uri.parse('$_base/api/download'),",
"              headers: {'Content-Type': 'application/json'},",
"              body: '{\"videoId\":\"$videoId\"}')",
"          .timeout(const Duration(seconds: 60));",
"      if (r.statusCode != 200) throw Exception();",
"      final um = RegExp(r'\"url\"\\s*:\\s*\"([^\"]+)\"').firstMatch(r.body);",
"      final tm = RegExp(r'\"title\"\\s*:\\s*\"([^\"]+)\"').firstMatch(r.body);",
"      if (um == null) throw Exception();",
"      final url = um.group(1)!.replaceAll(r'\\/', '/');",
"      final t2 = tm?.group(1) ?? title;",
"      final dl = await http.get(Uri.parse(url)).timeout(const Duration(seconds: 120));",
"      if (dl.statusCode != 200) throw Exception();",
"      final dir = await getExternalStorageDirectory();",
"      final base = dir?.path.replaceAll(RegExp(r'Android.*'), '') ?? '/storage/emulated/0/';",
"      final f = File('${base}Download/${title.replaceAll(RegExp(r'[\\\\/:*?\"<>|]'), '_')}.mp3');",
"      await f.parent.create(recursive: true);",
"      await f.writeAsBytes(dl.bodyBytes);",
"      _wvc?.evaluateJavascript(source: \"if(typeof showToast==='function') showToast('Download selesai: $t2');\");",
"    } catch (_) {",
"      _wvc?.evaluateJavascript(source: \"if(typeof showToast==='function') showToast('Download gagal, coba lagi');\");",
"    }",
"  }",
"",
"  void _openPlayer(Song song) {",
"    _currentSong = song;",
"    Navigator.of(context).push(PageRouteBuilder(",
"      pageBuilder: (_, __, ___) => PlayerScreen(",
"        song: song,",
"        onNext: () => _wvc?.evaluateJavascript(",
"            source: \"if(typeof playNextSimilarSong==='function') playNextSimilarSong();\"),",
"        onPrev: () => _wvc?.evaluateJavascript(",
"            source: \"if(typeof playPrevSong==='function') playPrevSong();\"),",
"      ),",
"      transitionsBuilder: (_, anim, __, child) => SlideTransition(",
"        position: Tween<Offset>(begin: const Offset(0, 1), end: Offset.zero)",
"            .animate(CurvedAnimation(parent: anim, curve: Curves.easeOut)),",
"        child: child,",
"      ),",
"    ));",
"  }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return PopScope(",
"      canPop: false,",
"      onPopInvokedWithResult: (didPop, _) async {",
"        if (didPop) return;",
"        if (await _onBack() && mounted) SystemNavigator.pop();",
"      },",
"      child: Scaffold(",
"        backgroundColor: const Color(0xFF0a0a0f),",
"        resizeToAvoidBottomInset: false,",
"        body: SafeArea(",
"          top: true,",
"          bottom: true,",
"          child: Stack(children: [",
"            InAppWebView(",
"              initialUrlRequest: URLRequest(url: WebUri(_base)),",
"              initialSettings: InAppWebViewSettings(",
"                javaScriptEnabled: true,",
"                domStorageEnabled: true,",
"                databaseEnabled: true,",
"                mediaPlaybackRequiresUserGesture: false,",
"                allowsInlineMediaPlayback: true,",
"                mixedContentMode: MixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW,",
"                useWideViewPort: true,",
"                loadWithOverviewMode: true,",
"                supportZoom: false,",
"                builtInZoomControls: false,",
"                displayZoomControls: false,",
"                cacheMode: CacheMode.LOAD_DEFAULT,",
"                userAgent: 'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',",
"              ),",
"              onWebViewCreated: (c) {",
"                _wvc = c;",
"                c.addJavaScriptHandler(",
"                  handlerName: 'playStream',",
"                  callback: (args) async {",
"                    final url    = args.isNotEmpty ? args[0].toString() : '';",
"                    final title  = args.length > 1 ? args[1].toString() : 'Auspoty';",
"                    final artist = args.length > 2 ? args[2].toString() : '';",
"                    final imgUrl = args.length > 3 ? args[3].toString() : '';",
"                    final vidId  = args.length > 4 ? args[4].toString() : '';",
"                    if (url.isEmpty) return;",
"                    try { WakelockPlus.enable(); } catch (_) {}",
"                    final song = Song(",
"                      videoId: vidId,",
"                      title: title,",
"                      artist: artist.isNotEmpty ? artist : 'Auspoty',",
"                      thumbnail: imgUrl,",
"                      streamUrl: url,",
"                    );",
"                    final item = MediaItem(",
"                      id: url,",
"                      title: title,",
"                      artist: artist.isNotEmpty ? artist : 'Auspoty',",
"                      artUri: imgUrl.isNotEmpty ? Uri.tryParse(imgUrl) : null,",
"                      displayTitle: title,",
"                      displaySubtitle: artist,",
"                    );",
"                    await audioHandler.playUrl(url, item, headers: {",
"                      'User-Agent': 'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',",
"                      'Origin': 'https://www.youtube.com',",
"                      'Referer': 'https://www.youtube.com/',",
"                    });",
"                    if (mounted) _openPlayer(song);",
"                  },",
"                );",
"                c.addJavaScriptHandler(",
"                  handlerName: 'pauseAudio',",
"                  callback: (args) async => audioHandler.pause(),",
"                );",
"                c.addJavaScriptHandler(",
"                  handlerName: 'resumeAudio',",
"                  callback: (args) async => audioHandler.play(),",
"                );",
"                c.addJavaScriptHandler(",
"                  handlerName: 'seekAudio',",
"                  callback: (args) async {",
"                    final pct = args.isNotEmpty ? double.tryParse(args[0].toString()) ?? 0.0 : 0.0;",
"                    final dur = audioHandler.duration.inMilliseconds;",
"                    if (dur > 0) {",
"                      await audioHandler.seek(Duration(milliseconds: (pct / 100 * dur).round()));",
"                    }",
"                  },",
"                );",
"                c.addJavaScriptHandler(handlerName: 'isAndroid', callback: (args) => true);",
"                c.addJavaScriptHandler(",
"                  handlerName: 'onMusicPlaying',",
"                  callback: (args) async { try { WakelockPlus.enable(); } catch (_) {} },",
"                );",
"                c.addJavaScriptHandler(",
"                  handlerName: 'downloadTrack',",
"                  callback: (args) async {",
"                    final vid   = args.isNotEmpty ? args[0].toString() : '';",
"                    final title = args.length > 1 ? args[1].toString() : 'lagu';",
"                    if (vid.isNotEmpty) _download(vid, title);",
"                  },",
"                );",
"                c.addJavaScriptHandler(",
"                  handlerName: 'openDownload',",
"                  callback: (args) async {",
"                    final url = args.isNotEmpty ? args[0].toString() : '';",
"                    if (url.isNotEmpty) {",
"                      final uri = Uri.parse(url);",
"                      if (await canLaunchUrl(uri)) await launchUrl(uri, mode: LaunchMode.externalApplication);",
"                    }",
"                  },",
"                );",
"                c.addJavaScriptHandler(",
"                  handlerName: 'getAccountName',",
"                  callback: (args) async {",
"                    final p = await SharedPreferences.getInstance();",
"                    return p.getString('accountName') ?? '';",
"                  },",
"                );",
"                c.addJavaScriptHandler(",
"                  handlerName: 'openGoogleLogin',",
"                  callback: (args) async {",
"                    await c.loadUrl(urlRequest: URLRequest(url: WebUri('$_base/login.html')));",
"                  },",
"                );",
"              },",
"              onLoadStart: (c, url) => setState(() => _loading = true),",
"              onLoadStop: (c, url) async {",
"                setState(() => _loading = false);",
"                final urlStr = url?.toString() ?? '';",
"                if (urlStr.contains('userData=')) {",
"                  final uri = Uri.parse(urlStr);",
"                  final ud = uri.queryParameters['userData'];",
"                  if (ud != null && ud.isNotEmpty) {",
"                    await c.evaluateJavascript(source: \"\"\"",
"                      (function(){",
"                        try{",
"                          var raw=decodeURIComponent(\\\"${Uri.encodeComponent(ud)}\\\");",
"                          localStorage.setItem('auspotyGoogleUser',raw);",
"                          var p=JSON.parse(raw);",
"                          if(typeof updateProfileUI==='function') updateProfileUI();",
"                          if(typeof updateGoogleLoginUI==='function') updateGoogleLoginUI();",
"                          if(typeof showToast==='function') showToast('Selamat datang, '+(p.name||'').split(' ')[0]+'!');",
"                          history.replaceState(null,'','/');",
"                        }catch(e){}",
"                      })()",
"                    \"\"\");",
"                  }",
"                }",
"                if (urlStr.contains('vercel.app') || urlStr.contains('clone2') || urlStr.isEmpty) {",
"                  await _inject(c);",
"                }",
"              },",
"              onCreateWindow: (c, action) async {",
"                final url = action.request.url?.toString() ?? '';",
"                if (url.isNotEmpty && url != 'about:blank') {",
"                  final uri = Uri.parse(url);",
"                  if (await canLaunchUrl(uri)) await launchUrl(uri, mode: LaunchMode.externalApplication);",
"                }",
"                return true;",
"              },",
"              onProgressChanged: (c, p) { if (p == 100) setState(() => _loading = false); },",
"              onPermissionRequest: (c, req) async => PermissionResponse(",
"                  resources: req.resources, action: PermissionResponseAction.GRANT),",
"              shouldOverrideUrlLoading: (c, nav) async {",
"                final url = nav.request.url?.toString() ?? '';",
"                const ok = ['vercel.app','youtube.com','ytimg.com','googleapis.com',",
"                  'gstatic.com','firebaseapp.com','firebase.google.com',",
"                  'accounts.google.com','google.com','googleusercontent.com'];",
"                for (final d in ok) { if (url.contains(d)) return NavigationActionPolicy.ALLOW; }",
"                if (url.startsWith('about:') || url.startsWith('blob:') || url.startsWith('data:')) {",
"                  return NavigationActionPolicy.ALLOW;",
"                }",
"                if (url.startsWith('http') && nav.isForMainFrame) {",
"                  final uri = Uri.parse(url);",
"                  if (await canLaunchUrl(uri)) await launchUrl(uri, mode: LaunchMode.externalApplication);",
"                  return NavigationActionPolicy.CANCEL;",
"                }",
"                return NavigationActionPolicy.ALLOW;",
"              },",
"            ),",
"            if (_loading)",
"              Container(",
"                color: const Color(0xFF0a0a0f),",
"                child: const Center(",
"                  child: Column(",
"                    mainAxisAlignment: MainAxisAlignment.center,",
"                    children: [",
"                      Icon(Icons.music_note, color: Color(0xFF7c6af7), size: 64),",
"                      SizedBox(height: 16),",
"                      Text('Auspoty', style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold, letterSpacing: 2)),",
"                      SizedBox(height: 24),",
"                      CircularProgressIndicator(color: Color(0xFF7c6af7), strokeWidth: 2),",
"                    ],",
"                  ),",
"                ),",
"              ),",
"          ]),",
"        ),",
"      ),",
"    );",
"  }",
"",
"  Future<void> _inject(InAppWebViewController c) async {",
"    await c.evaluateJavascript(source: r\"\"\"",
"      (function(){",
"        var id='__af__',o=document.getElementById(id);if(o)o.remove();",
"        var s=document.createElement('style');s.id=id;",
"        s.textContent=`.bottom-nav{position:fixed!important;bottom:0!important;left:0!important;right:0!important;height:60px!important;display:flex!important;justify-content:space-around!important;align-items:center!important;padding:0!important;background:rgba(10,10,15,0.95)!important;backdrop-filter:blur(30px)!important;border-top:1px solid rgba(255,255,255,0.1)!important;z-index:1000!important;}.nav-item{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:3px!important;font-size:10px!important;min-width:60px!important;height:60px!important;cursor:pointer!important;color:rgba(255,255,255,0.5)!important;}.nav-item.active{color:#7c6af7!important;}.nav-item svg{width:22px!important;height:22px!important;fill:currentColor!important;}body{padding-bottom:160px!important;}.mini-player{bottom:68px!important;}.toast-notification.show{bottom:80px!important;}`;",
"        document.head.appendChild(s);",
"      })();",
"    \"\"\");",
"  }",
"}",
]

content = "\n".join(lines) + "\n"

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"OK: written {len(content)} chars")

with open(path, 'r', encoding='utf-8') as f:
    txt = f.read()
if 'home.dart' in txt or 'HomeScreen' in txt:
    print("ERROR: still has home.dart!")
else:
    print("OK: clean - no home.dart")
